version: '3'

services:
  pyko:
    build: ./pyko
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./pyko:/pyko
      - ./pyko/logs:/pyko/logs
      - ./home/projects/pyko/pyko/static:/pyko/static
      - ./home/projects/pyko/pyko/media:/pyko/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod

  nginx:
    build: ./nginx
    restart: always
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - ./home/projects/pyko/pyko/static:/pyko/static
      - ./home/projects/pyko/pyko/media:/pyko/media
    depends_on:
      - pyko