version: '3'

services:
  web:
    build: ./pyko
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/projects/pyko/static
      - media_volume:/home/projects/pyko/media

    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
  nginx:
    build: ./nginx
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/projects/pyko/static
      - media_volume:/home/projects/pyko/media
    depends_on:
      - web
  db:
    image: postgres
    environment:
      - POSTGRES_USER = postgres
          
volumes:
  static_volume:
  media_volume: