version: '3'

services:
  pyko:
    build: ./pyko
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./pyko:/pyko
      - ./pyko/logs:/pyko/logs
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod

  nginx:
    build: ./nginx
    restart: always
    image: nginx:1.18.0
    ports:
      - "80:80"
    depends_on:
      - pyko