# Generated by Django 4.2.2 on 2023-11-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('파이썬', 'Python'), ('웹 개발', 'Web Development'), ('자동화 및 스크립팅', 'Automation and Scripting'), ('크롤링', 'Web Crawling'), ('데이터 분석', 'Data Analysis'), ('시각화', 'Visualization'), ('머신러닝', 'Machine learning'), ('잡담', 'anything')], default='웹 개발', max_length=50),
        ),
    ]
