# Generated by Django 4.2.2 on 2023-11-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='소개글을 작성해보세요', max_length=500),
        ),
    ]
